# Generated by Django 5.2.6 on 2025-09-16 14:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('rating', models.FloatField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField()),
                ('category', models.CharField(choices=[('sneakers', 'Sneakers'), ('boots', 'Boots'), ('sandals', 'Sandals'), ('formal', 'Formal Shoes'), ('sports', 'Sports Shoes'), ('casual', 'Casual Shoes'), ('loafers', 'Loafers'), ('heels', 'Heels'), ('flats', 'Flats'), ('slippers', 'Slippers'), ('other', 'Other')], default='update', max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
