# Generated by Django 5.2.6 on 2025-09-13 04:16

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_delete_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('sneakers', 'Sneakers'), ('boots', 'Boots'), ('sandals', 'Sandals'), ('formal', 'Formal Shoes'), ('sports', 'Sports Shoes'), ('casual', 'Casual Shoes'), ('loafers', 'Loafers'), ('heels', 'Heels'), ('flats', 'Flats'), ('slippers', 'Slippers'), ('other', 'Other')], default='update', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
